[package]
name = "rusty_runways_gui"
version = "3.0.3"
edition = "2024"

[dependencies]
rusty_runways_core = { path = "../core" }
eframe = "0.32.0"
rand = { version = "0.8", features = ["std_rng"] }
serde_yaml = "0.9"
rfd = "0.14"
