[package]
name = "RustyRunways"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rand = { version = "0.8", features = ["std_rng"] }
strum = "0.27"
strum_macros = "0.27"
strsim = "0.10"
serde_json = "1.0"
pyo3 = "0.25.1"
rustyline = "16.0.0"


