[build-system]
requires = ["maturin>=1.4"]
build-backend = "maturin"

[project]
name = "rusty-runways"
version = "0.1.0"
description = "Python bindings for Rusty Runways"
requires-python = ">=3.8"
dependencies = []

[tool.maturin]
module-name = "rusty_runways_py"
