name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Tarpaulin
        run: |
          # run all tests, produce XML for Codecov
          cargo tarpaulin \
            --all-features \
            --workspace \
            --timeout 120 \
            --out Xml

      - name: Upload to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cobertura.xml
          fail_ci_if_error: true
          verbose: true
