name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Tarpaulin
        run: |
          # run all tests, produce XML for Codecov
          cargo tarpaulin \
            --all-features \
            --workspace \
            --exclude rusty_runways_py \
            --timeout 120 \
            --out Xml \
            --output-dir coverage
          ls -lah coverage

      - name: Upload to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/cobertura.xml
          flags: rust
          fail_ci_if_error: true
          verbose: true
