name: Publish Python Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            manylinux: manylinux2014
            args: >
              --profile release -m crates/py/Cargo.toml --sdist --skip-existing
          - os: macos-13
            target: universal2-apple-darwin
            args: >
              --profile release -m crates/py/Cargo.toml --sdist --skip-existing
          - os: windows-latest
            args: >
              --profile release -m crates/py/Cargo.toml --sdist --skip-existing

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Build and publish (PyPI)
        uses: messense/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          maturin-version: "v1.9.3"
          command: publish
          args: ${{ matrix.args }}
          target: ${{ matrix.target }}
          manylinux: ${{ matrix.manylinux }}
          sccache: true
