name: Python Dev Tests

on:
  push:
    paths:
      - 'crates/py/**'
      - '.github/workflows/python-dev-tests.yml'
  pull_request:
    paths:
      - 'crates/py/**'
      - '.github/workflows/python-dev-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build and run tests
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip maturin pytest gymnasium
          # Use the pyproject so maturin picks up pure-Python package under python/
          maturin develop -m crates/py/pyproject.toml
          pytest crates/py/tests
