name: Python Dev Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build and run tests
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip maturin pytest
          maturin develop -m crates/py/Cargo.toml
          pytest crates/py/tests
